import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "tippy.js/dist/tippy.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "SISCON",
	description: "Generated by David Iglesias",
	icons: "/favicon.png",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="text-xs h-screen">{children}</main>
			</body>
		</html>
	);
}
